### ISSUE TITLE
Request for the new Shelly Floot

### ISSUE THREAD

**Issue by GeminiServer** [markus7017/org.openhab.binding.shelly#13]
Hi Markus, 
great work. I just installed and works great. Currently i miss the New Shelly Flood (may be it is to new). Would be cool if you can also add support for that device. Currently there are no api description for that device available.

cheers, 
Erkan

The API-Description is now available: https://shelly-api-docs.shelly.cloud/#shelly-flood

**Comment by markus7017** [comment]
please check out the latest snapshot release, it should work fine with that
