### ISSUE TITLE
calibrating channel existing anymore

### ISSUE THREAD

**Issue by fab33** [markus7017/org.openhab.binding.shelly#16]
Hi,
On documentation there is a mention for calibrating channel for roller shutters. I can't see it in https://github.com/markus7017/org.openhab.binding.shelly/blob/master/ESH-INF/thing/relay.xml
Will it be implemented in the future ?

**Comment by markus7017** [comment]
The question is: Do you need it? Calibration has to be performed once. The binding integrates only a very few settings (like the AutoOn/Off timer), but provides maximum support for status attributes.

Are you looking for
- a command to trigger calibration -> use the Shelly App
- an indication if the calibration has been performed or the device is in calibration mode? -> Please describe the user case

In general it should be no big effort, but adding more channels might confuse the user.
