### ISSUE TITLE
Shelly HT - issues with hostname changes and sensor udates

### ISSUE THREAD

**Issue by UweHD** [markus7017/org.openhab.binding.shelly#8]
Issue #1: Hostname changes
When using the Shelly HT heat and humidity sensors, it is crucial not to alter the hostname on your network after you autodiscovered the Shelly as thing in openHAB. The hostname will become a variable necessary for communication (as seen in the Shelly web interface "action" tab). Maybe this variable can be changed to the Shelly's MAC to avoid user error?

Issue #2: Sensor updates
Even if you successfully discovered and connected the HT to openHAB, the sensor readinds tend not to update after a while. This seems to be connected with the sleep interval of the battery driven sensors.
The native Shelly App reads the updated values once the Shelly wakes up (the sensor wake up is driven by temperature changes), but the openHAB instance obviously not (always) gets the updated data. I haven't figured out the reason yet, but I assume it's because of update intervals in openHAB not in sync with the "wake up" events of the Shelly

**Comment by UweHD** [comment]
One thing to mention:
When you manually wake up the Shelly HT by pressing the (internal) button, it seems to update the sensor readings in openHAB. The button wakes up the Shelly, so the sensor reading are transferred. Temp changes also automatically wake up the Shelly but in that case the readings don't make it into openHAB for whatever reason.

**Comment by markus7017** [comment]
I made a change to use the mDNS service name rather than the hostname as device name, also for the event urls. However, I'm not sure if the shelly uses it's hostname for advertisement. Could you please repeat your test.

**Comment by markus7017** [comment]
please open a seperate Issue for the sensor update issue above
