### ISSUE TITLE
Roller position value is reversed

### ISSUE THREAD

**Issue by dacchio** [markus7017/org.openhab.binding.shelly#9]
The position  percentage in the binding is reversed compared to shelly's so the blind icon is displayed wrong  (closed when open and vice versa).

This is indipendent from the  "swap inputs" and "reverse direction" set up of the shelly. 

I think a convertion is needed to show the blind icon in the correct way.

**Comment by markus7017** [comment]
fixed with the latest build

please verify

**Comment by markus7017** [comment]
use beta1-pre2
https://github.com/markus7017/org.openhab.binding.shelly/blob/beta1-pre2/target/org.openhab.binding.shelly-2.4.0-SNAPSHOT.jar

**Comment by markus7017** [comment]
just noticed that the way back (manuel switch->OH) needs also to be adjusted

**Comment by markus7017** [comment]
done
